---
- name: debian | adding Owncloud repo key
  apt_key:
    url: "{{ owncloud_debian_repo_key }}"
    state: present

- name: debian | adding Owncloud debian repo
  apt_repository:
    repo: "{{ owncloud_debian_repo }}"
    state: present

- name: debian | installing Owncloud
  apt:
    name: owncloud
    state: present
